/*
 * @(#)ServiceContextListener.java	1.13 08/09/15
 * 
 * Copyright � 2008 Sun Microsystems, Inc. All rights reserved. 
 * Use is subject to license terms.
 * 
 */

package javax.tv.service.selection;

import java.util.EventListener;

/**
 * The <code>ServiceContextListener</code> interface is implemented by
 * applications wishing to receive events related to service contexts.
 * 
 * @see ServiceContext
 */
public interface ServiceContextListener extends EventListener {

    /**
     * Notifies the <code>ServiceContextListener</code> of an event generated by
     * a <code>ServiceContext</code>.
     * 
     * @param e
     *            The generated event.
     */
    public abstract void receiveServiceContextEvent(ServiceContextEvent e);
}
