/*
 * @(#)ControllerEvent.java	1.3 08/09/15
 * 
 * Copyright � 2008 Sun Microsystems, Inc. All rights reserved. 
 * Use is subject to license terms.
 * 
 */

package javax.media;

/**
 * <code>ControllerEvent</code> is the base class for events generated by a
 * <CODE>Controller</CODE>.
 * 
 * These events are used by <CODE>ControllerListener</CODE>.
 * 
 * <h2>Java Beans Compatibility</h2> This class is designed to support the Java
 * Beans event model. In order to enable
 * 
 * @see Controller
 * @see ControllerListener
 * @see MediaEvent
 * @version 1.14, 98/03/28
 */

public class ControllerEvent extends java.util.EventObject implements
	MediaEvent {

    Controller eventSrc;

    public ControllerEvent(Controller from) {
	super(from);
	eventSrc = from;
    }

    /**
     * Get the <CODE>Controller</CODE> that posted this event. The returned
     * <CODE>Controller</CODE> has at least one active listener. (The
     * <CODE>addListener</CODE> method has been called on the
     * <CODE>Controller</CODE>).
     * 
     * @return The <CODE>Controller</CODE> that posted this event.
     */
    public Controller getSourceController() {
	return eventSrc;
    }

    public Object getSource() {
	return eventSrc;
    }

    /**
     * Returns the String representation of this event's values.
     */
    public String toString() {
	return getClass().getName() + "[source=" + eventSrc + "]";
    }
}
