/*
 * @(#)GainChangeListener.java	1.4 08/09/15
 * 
 * Copyright � 2008 Sun Microsystems, Inc. All rights reserved. 
 * Use is subject to license terms.
 * 
 */

package javax.media;

/**
 * <CODE>GainChangeListener</CODE> is an interface for handling
 * <code>GainChangeEvents</code> generated by <code>GainControls</code>.
 * 
 * <h2>Java Beans support</h2> It is required that any implementation of this
 * object is sub-classed either from java.util.EventListener, or
 * sunw.util.EventListener.
 * 
 * 
 * @see GainControl
 * @see GainChangeEvent
 * 
 * @version 1.13, 98/03/28.
 */
public interface GainChangeListener extends java.util.EventListener {

    /**
     * This method is called to deliver a <code>GainChangeEvent</code> when the
     * state of a <code>GainControl</code> changes.
     * 
     * @param event
     *            The event generated.
     */
    void gainChange(GainChangeEvent event);
}
