/*
 * @(#)StopTimeChangeEvent.java	1.3 08/09/15
 * 
 * Copyright � 2008 Sun Microsystems, Inc. All rights reserved. 
 * Use is subject to license terms.
 * 
 */

package javax.media;

/**
 * A <code>StopTimeChangeEvent</code> is generated by a <code>Controller</code>
 * when its stop time has changed.
 * 
 * @see Controller
 * @see ControllerListener
 * @version 1.14, 98/03/28.
 */
public class StopTimeChangeEvent extends ControllerEvent {

    Time stopTime;

    public StopTimeChangeEvent(Controller from, Time newStopTime) {
	super(from);
	stopTime = newStopTime;
    }

    /**
     * Get the new stop-time for the <code>Controller</code> that generated this
     * event.
     * 
     * @return The new stop time for the <code>Controller</code> that generated
     *         this event.
     */
    public Time getStopTime() {
	return stopTime;
    }

    /**
     * Returns the String representation of this event's values.
     */
    public String toString() {
	return getClass().getName() + "[source=" + eventSrc + ",stopTime="
		+ stopTime + "]";
    }
}
